name: "Lint for Pull Requests"

on:
  pull_request:
    paths:
      - 'docs/**/*.md'
      - .github/workflows/markdown-lint.yml
      - .vale.ini

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Lint markdown files
        run: |
          npx markdownlint-cli '*.md' -i LICENSE.md -i CODE_OF_CONDUCT.md

      - name: Vale
        uses: errata-ai/vale-action@v1
        with:
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

          # Optional
          files: __onlyModified
          onlyAnnotateModifiedLines: true

        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

